name: Continuous integration

on: [push, pull_request]

jobs:
  linux:
    name: CI
    runs-on: ubuntu-20.04
    timeout-minutes: 60
    steps:
      - name: Download repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Generate Makefile
        run: cmake -S . -B build/ -G "Unix Makefiles" 

      - name: Build
        run: cmake --build build/ -j 2

      - name: Run tests
        run: ./build/tests